# Generated by Django 5.0.13 on 2025-08-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hustledesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
